config/routes.rb
Rails.application.routes.draw do

  # Clearance Routes
  resource :session, controller: 'sessions', only: [:create]

  get '/login', to: 'clearance/sessions#new', as: :sign_in
  delete '/sign_out', to: 'sessions#destroy', as: :sign_out

  # App Routes
  root 'pages#home'

  constraints Clearance::Constraints::SignedIn.new do
    get 'admin', to: 'admin#index', as: :admin
    patch 'admin', to: 'admin#update'

    scope 'admin' do
      resources :samples, only: :update
      resources :parallaxes, only: :update
    end
  end

  constraints Clearance::Constraints::SignedOut.new do
    get 'admin', to: 'clearance/sessions#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/krissi.rb
class Krissi < ApplicationRecord
  has_attached_file :bio_image, styles: { medium: '1000x1000#' }, default_url: 'https://scontent.cdninstagram.com/t51.2885-15/s320x320/e35/18809160_239275669889184_840459996712927232_n.jpg'
  validates_attachment_content_type :bio_image, content_type: /\Aimage\/.*\z/
  has_many :samples, dependent: :destroy
  has_many :parallaxes, dependent: :destroy
  validate :only_one, on: :create
  validates :linkedin, presence: true
  validates :instagram, presence: true
  validates :facebook, presence: true
  validates :bio_body, presence: true
  validates :contact_body, presence: true
  before_validation :to_nil

  private

  def only_one
    if Krissi.count == 1
      errors.add(:base, 'There can only be one Krissi')
    end
  end

  def to_nil
    attributes.each { |a| a = nil if a == '' }
  end
end

app/models/parallax.rb
class Parallax < ApplicationRecord
  belongs_to :krissi
  has_attached_file :image, styles: { large:  '1920x1080' }, convert_options: { large: '-quality 90' }, default_url: 'https://via.placeholder.com/3840x2160.jpg'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  before_validation :to_nil
  validate :only_three, on: :create

  private

  def only_three
    if Sample.count == 3
      errors.add(:base, 'There can only be three parallax images')
    end
  end

  def to_nil
    attributes.each { |a| a = nil if a == '' }
  end
end

app/models/sample.rb
class Sample < ApplicationRecord
  belongs_to :krissi
  has_attached_file :image, styles: { thumb: '640x640#' }, default_url: 'https://via.placeholder.com/640x640.jpg'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :caption, presence: true
  validates :category, presence: true
  validates :alt, presence: true
  before_validation :to_nil
  validate :only_eight, on: :create

  private

  def only_eight
    if Sample.count == 8
      errors.add(:base, 'There can only be eight sample images')
    end
  end

  def to_nil
    attributes.each { |a| a = nil if a == '' }
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :set_krissi

  def index; end

  def update
    if @krissi.update_attributes!(admin_attributes)
      flash[:success] = 'Update successful'
      redirect_to admin_url
    else
      flash[:failure] = 'Update failed'
      redirect_to admin_url
    end
  end

  private

  def set_krissi
    @krissi = Krissi.first
  end

  def admin_attributes
    params.require(:krissi).permit(:linkedin, :instagram, :facebook, :contact_body, :bio_body, :bio_image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @krissi = Krissi.first
    @samples = Sample.all.order(id: :asc)
  end
end

app/controllers/parallaxes_controller.rb
class ParallaxesController < ApplicationController
  before_action :set_parallax

  def update
    if parallax_params && @parallax.update_attributes!(parallax_params)
      flash[:success] = 'Update successful'
      redirect_to admin_url
    else
      flash[:failure] = 'Update failed'
      redirect_to admin_url
    end
  end

  private

  def set_parallax
    @parallax = Parallax.find(params[:id])
  end

  def parallax_params
    return false unless params[:parallax]
    params.require(:parallax).permit(:image)
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample

  def update
    if @sample.update_attributes!(sample_params)
      flash[:success] = 'Update successful'
      redirect_to admin_url
    else
      flash[:failure] = 'Update failed'
      redirect_to admin_url
    end
  end

  private

  def set_sample
    @sample = Sample.find(params[:id])
  end

  def sample_params
    params.require(:sample).permit(:caption, :category, :alt, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

  def create
    @user = authenticate(params)

    sign_in(@user) do |status|
      if status.success?
        flash[:success] = 'Logged in'
        redirect_back_or url_after_create
      else
        flash[:failure] = status.failure_message
        redirect_to sign_in_url
      end
    end
  end

  def destroy
    sign_out
    flash[:success] = 'Logged out'
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/_admin_form.html.erb
<h3 class="uk-heading-divider uk-text-center custom-font-1" style="background-color: white; margin-bottom: 0 !important; padding-top: 10px !important;">Info</h3>
<div class="uk-width-1-1" style="padding: 0 1rem;">
    <%= form_for @krissi, url: admin_path(@krissi), method: :patch, html: { class: 'uk-form-stacked' } do |f| %>
        <div class="uk-margin">
            <%= f.label :linkedin, class: 'uk-form-label custom-font-1', for: 'krissi_linkedin' %>
            <div class="uk-form-controls">
                <%= f.text_field :linkedin, class: 'uk-input custom-font-2' %>
            </div>
        </div>
        <div class="uk-margin">
            <%= f.label :instagram, class: 'uk-form-label custom-font-1', for: 'krissi_instagram' %>
            <div class="uk-form-controls">
                <%= f.text_field :instagram, class: 'uk-input custom-font-2' %>
            </div>
        </div>
        <div class="uk-margin">
            <%= f.label :facebook, class: 'uk-form-label custom-font-1', for: 'krissi_facebook' %>
            <div class="uk-form-controls">
                <%= f.text_field :facebook, class: 'uk-input custom-font-2' %>
            </div>
        </div>
        <div class="uk-margin">
            <%= f.label :contact_body, class: 'uk-form-label custom-font-1', for: 'krissi_contact_body' %>
            <div class="uk-form-controls">
                <%= f.text_area :contact_body, class: 'uk-textarea custom-font-2' %>
            </div>
        </div>
        <div class="uk-margin">
            <%= f.label :bio_body, class: 'uk-form-label custom-font-1', for: 'krissi_bio_body' %>
            <div class="uk-form-controls">
                <%= f.text_area :bio_body, class: 'uk-textarea custom-font-2' %>
            </div>
        </div>
        <div class="uk-margin">
            <label for="bio_image_show" class="uk-form-label custom-font-1">Current Image</label>
            <div class="uk-form-controls">
                <%= image_tag @krissi.bio_image.url, id: 'bio_image_show' %>
            </div>
        </div>
        <div class="uk-margin">
            <%= f.label :bio_image, 'Leave this empty if you want to keep the current photo', class: 'uk-form-label custom-font-1', for: 'krissi_bio_image' %>
            <div class="uk-form-controls" style="overflow: hidden;">
                <%= f.file_field :bio_image, class: 'custom-font-2' %>
            </div>
        </div>
        <div class="uk-margin">
            <%= f.submit 'Save', class: 'uk-button uk-button-primary uk-width-1-1 custom-font-1' %>
        </div>
    <% end %>
</div>

app/views/admin/_footer.html.erb
<nav class="uk-navbar-container" style="background-color: #222 !important; height: 10vh !important; z-index: 0;" uk-navbar>
    <div class="uk-navbar-left"></div>
    <div class="uk-navbar-center custom-font-1">
        <ul class="uk-navbar-nav">
            <li class="uk-navbar-item" style="height: 10vh !important">
                <div>
                    <%= link_to 'Back', root_path, class: 'custom-font-1', style: 'color: #d3d3d3;' %>
                </div>
            </li>
            <li class="uk-navbar-item" style="height: 10vh !important">
                <div>
                    <%= link_to 'Sign Out', sign_out_path, class: 'custom-font-1', style: 'color: #d3d3d3;', method: :delete %>
                </div>
            </li>
        </ul>
    </div>
    <div class="uk-navbar-right" ></div>
</nav>

app/views/admin/_header.html.erb
<div class="uk-light">
    <nav class="uk-navbar-container" style="height: 10vh !important; z-index: 981; background-color: #222;" uk-navbar>
        <div class="uk-navbar-center">
            <div class="uk-navbar-center-left">
            </div>
            <a href="" class="uk-navbar-item uk-logo handwriting">Welcome, Krissi</a>
            <div class="uk-navbar-center-right">
            </div>
        </div>
    </nav>
</div>

app/views/admin/_parallax_list.html.erb
<h3 class="uk-heading-divider uk-text-center custom-font-1" style="background-color: white; margin-bottom: 0 !important; padding-top: 10px !important;">Parallaxes</h3>
<div class="uk-grid-collapse uk-child-width-1-1" uk-grid></div>
    <% @krissi.parallaxes.order(id: :asc).find_each do |p| %>
        <%= link_to '', class: 'uk-inline-clip uk-transition-toggle', 'uk-toggle' => "target: ##{p.id}" do %>
            <%= image_tag p.image.url, class: 'uk-width-1-1', style: 'backface-visibility: hidden;' %>
            <div class="uk-transition-slide-bottom uk-position-bottom uk-overlay uk-overlay-default">
                <p class="uk-h4 uk-margin-remove uk-text-center custom-font-1">Edit Parallax</p>
            </div>
            <div id="<%= p.id %>" uk-modal>
                <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">
                    <button class="uk-modal-close-default" type="button" uk-close></button>
                    <h2 class="uk-modal-title custom-font-1">Edit Parallax</h2>
                    <%= image_tag p.image.url, class: 'uk-width-1-1' %>
                    <div class="uk-width-1-1">
                        <%= form_for p, html: { class: 'uk-form-stacked uk-width-1-1' } do |f| %>
                            <div class="uk-margin">
                                <%= f.label :image, 'Leave this empty if you want to keep the current photo', class: 'uk-form-label custom-font-1', for: 'sample_image' %>
                                <%= f.file_field :image, class: 'custom-font-2' %>
                            </div>
                            <div class="uk-margin">
                                <%= f.submit 'Save', class: 'uk-button uk-button-primary uk-width-1-1 custom-font-1' %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/admin/_sample_list.html.erb
<h3 class="uk-heading-divider uk-text-center custom-font-1" style="background-color: white; margin-bottom: 0 !important; padding-top: 10px !important;">Samples</h3>
<div class="uk-grid-collapse uk-child-width-1-1" uk-grid>
    <% @krissi.samples.order(id: :asc).find_each do |s| %>
        <%= link_to '', class: 'uk-inline-clip uk-transition-toggle', 'uk-toggle' => "target: ##{s.id}" do %>
            <%= image_tag s.image.url(:thumb), class: 'uk-width-1-1', style: 'backface-visibility: hidden;' %>
            <div class="uk-transition-slide-bottom uk-position-bottom uk-overlay uk-overlay-default">
                <p class="uk-h4 uk-margin-remove uk-text-center custom-font-1">Edit Sample</p>
            </div>
            <div id="<%= s.id %>" uk-modal>
                <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">
                    <button class="uk-modal-close-default" type="button" uk-close></button>
                    <h2 class="uk-modal-title custom-font-1">Edit Sample</h2>
                    <%= image_tag s.image.url(:thumb), class: 'uk-width-1-1' %>
                    <div class="uk-width-1-1">
                        <%= form_for s, html: { class: 'uk-form-stacked uk-width-1-1' } do |f| %>
                            <div class="uk-margin">
                                <%= f.label :caption, class: 'uk-form-label custom-font-1', for: 'sample_caption' %>
                                <%= f.text_field :caption, class: 'uk-input custom-font-2' %>
                            </div>
                            <div class="uk-margin">
                                <%= f.label :category, class: 'uk-form-label custom-font-1', for: 'sample_category' %>
                                <%= f.text_field :category, class: 'uk-input custom-font-2' %>
                            </div>
                            <div class="uk-margin">
                                <%= f.label :alt, 'Describe the photo (for google)', class: 'uk-form-label custom-font-1', for: 'sample_alt' %>
                                <%= f.text_field :alt, class: 'uk-input custom-font-2' %>
                            </div>
                            <div class="uk-margin">
                                <%= f.label :image, 'Leave this empty if you want to keep the current photo', class: 'uk-form-label custom-font-1', for: 'sample_image' %>
                                <%= f.file_field :image, class: 'custom-font-2' %>
                            </div>
                            <div class="uk-margin">
                                <%= f.submit 'Save', class: 'uk-button uk-button-primary uk-width-1-1 custom-font-1' %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/admin/index.html.erb
<%= render 'header' %>

<div style="height: 80vh;" class="uk-grid-collapse uk-child-width-1-3" uk-grid>
    <div style="backface-visibility: hidden; height: 80vh;" class="uk-section-muted uk-overflow-auto">
        <%= render 'admin_form' %>
    </div>
    <div style="backface-visibility: hidden; height: 80vh;" class="uk-section-muted uk-overflow-auto">
        <%= render 'sample_list' %>
    </div>
    <div style="backface-visibility: hidden; height: 80vh;" class="uk-section-muted uk-overflow-auto">
        <%= render 'parallax_list' %>
    </div>
</div>

<%= render 'footer' %>

app/views/layouts/_favicons.html.erb
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <title><%= 'Admin | ' if signed_in? %>Krissi Flynn | Melbourne Photographer</title>
        <meta name="description" content="Welcome to the portfolio of Melbourne photographer, Krissi Flynn. See contact section for booking info." />
        <meta property="og:title" content="Krissi Flynn Photography" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="http://www.krissiflynn.com.au/" />
        <meta property="og:image" content="http://www.krissiflynn.com.au/assets/koala.jpg" />
        <meta property="og:description" content="Welcome to the portfolio of Melbourne photographer, Krissi Flynn." />
        <meta name=”viewport” content=”width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=0" />

        <%= render 'layouts/favicons' %>

        <link href="https://fonts.googleapis.com/css?family=IM+Fell+Double+Pica|Quicksand" rel="stylesheet">
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'true' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>

        <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
        <script type="application/ld+json">
            {
                "@context" : "http://schema.org",
                "@type" : "LocalBusiness",
                "name" : "Krissi Flynn",
                "image" : "https://s3-ap-southeast-2.amazonaws.com/krissi-flynn-portfolio/krissis/bio_images/000/000/002/medium/20476154_509061992763503_3599334325584470391_n.jpg?1504847779",
                "telephone" : "+61 475 067 450",
                "email" : "krissiflynnphotography@gmail.com",
                "address" : {
                    "@type" : "PostalAddress",
                    "addressLocality" : "Melbourne",
                    "addressRegion" : "Victoria",
                    "addressCountry" : "Australia"
                }
            }
        </script>
    </head>

    <body>
        <% unless flash.empty? %>
            <script>
                <% flash.each do |name, message| %>
                    <%= "UIkit.notification('#{message}', {pos: 'bottom-right', status: '#{name == 'success' ? 'success' : 'danger'}'});".html_safe %>
                <% end %>
            </script>
        <% end %>
        <%= yield %>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-106092817-1', 'auto');
          ga('send', 'pageview');

        </script>
    </body>
</html>

app/views/pages/_bio.html.erb
<div class="uk-section-muted uk-child-width-1-1 uk-grid-collapse page-section" uk-grid>
    <%= render 'parallax', image: @krissi.parallaxes.second.image %>
    <div id="third-section">
        <div class="uk-card uk-card-default uk-card-small" uk-sticky="offset: 80; bottom: true">
            <div class="uk-text-center uk-card-body uk-text-lead handwriting">
                All about Krissi
            </div>
        </div>
        <article class="uk-comment uk-comment-primary">
            <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
                <div class="uk-width-1-2@m uk-width-1-1@s info-text uk-align-center">
                    <%= simple_format(@krissi.bio_body.html_safe, class: 'uk-text-center custom-font-2') %>
                </div>
                <div class="uk-width-1-2@m uk-width-1-1@s">
                    <%= image_tag @krissi.bio_image.url(:medium), class: 'uk-align-center uk-border-rounded uk-height-max-large' %>
                </div>
            </header>
        </article>
    </div>
</div>

app/views/pages/_contact.html.erb
<div class="uk-section-muted uk-child-width-1-1 uk-grid-collapse page-section" uk-grid>
    <%= render 'parallax', image: @krissi.parallaxes.first.image %>
    <div id="second-section">
        <div class="uk-card uk-card-default uk-card-small" uk-sticky="offset: 80; bottom: true">
            <div class="uk-text-center uk-card-body uk-text-lead handwriting">
                Hire me!
            </div>
        </div>
        <article class="uk-comment uk-comment-primary">
            <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
                <div class="uk-width-1-1">
                    <div class="uk-width-1-1">
                        <p class="uk-text-center">
                            <%= link_to @krissi.linkedin, class: 'ui linkedin button', target: '_blank', rel: 'noopener' do %>
                                <i class="linkedin icon"></i>
                                LinkedIn
                            <% end %>
                            <%= link_to @krissi.facebook, class: 'ui facebook button', target: '_blank', rel: 'noopener' do %>
                                <i class="facebook icon"></i>
                                Facebook
                            <% end %>
                            <%= link_to @krissi.instagram, class: 'ui instagram button', target: '_blank', rel: 'noopener' do %>
                                <i class="instagram icon"></i>
                                Instagram
                            <% end %>
                        </p>
                    </div>
                    <div class="uk-width-1-1 info-text uk-align-center">
                        <%= simple_format(@krissi.contact_body.html_safe, class: 'uk-text-center custom-font-2') %>
                    </div>
                </div>
            </header>
        </article>
    </div>
</div>

app/views/pages/_footer.html.erb
<nav class="uk-navbar-container" style="background-color: #222 !important; height: 80px !important;" uk-navbar>
    <div class="uk-navbar-left">
        <% if signed_in? %>
            <ul class="uk-navbar-nav">
                <li class="uk-navbar-item">
                    <div>
                        <%= link_to 'Sign Out', sign_out_path, class: 'custom-font-1', style: 'color: #d3d3d3;', method: :delete %>
                    </div>
                </li>
            </ul>
        <% else %>
            <ul class="uk-navbar-nav">
                <li class="uk-navbar-item">
                    <div>
                        <p class="uk-margin-remove" style="color: #d3d3d3; font-family: 'Time New Roman', serif;">ABN: 76994944092</p>
                    </div>
                </li>
            </ul>
        <% end %>
    </div>
    <div class="uk-navbar-center custom-font-1">
        <ul class="uk-navbar-nav">
            <li class="uk-navbar-item">
                <div>
                    <a style="color: #d3d3d3;" class="custom-font-1" href="mailto:jordan.ellis.lynch@gmail.com?Subject=Krissi%20Flynn%20Portfolio">Contact Admin</a>
                </div>
            </li>
            <li class="uk-navbar-item">
                <div>
                    <a style="color: #d3d3d3;" class="custom-font-1" href="https://www.github.com/jordy-el" target="_blank" rel="noopener">Created by Jordan Ellis-Lynch</a>
                </div>
            </li>
            <li class="uk-navbar-item">
                <div>
                    <a style="color: #d3d3d3;" class="custom-font-1" href="/admin">Admin Panel</a>
                </div>
            </li>
        </ul>
    </div>
    <div class="uk-navbar-right"></div>
</nav>

app/views/pages/_links.html.erb
<div class="uk-section-muted uk-child-width-1-1 uk-grid-collapse page-section" uk-grid>
    <%= render 'parallax', image: @krissi.parallaxes.third.image %>
    <div id="fourth-section">
        <div class="uk-card uk-card-default uk-card-small" uk-sticky="offset: 80; bottom: true">
            <div class="uk-text-center uk-card-body uk-text-lead handwriting">
                Just some nice links
            </div>
        </div>
        <div class="uk-width-1-1">
            <p class="uk-text-center custom-font-2"></p>
        </div>
    </div>
</div>

app/views/pages/_loader.html.erb
<!--<div id="page-loader" class="uk-position-center uk-width-1-1 uk-height-1-1 uk-position-fixed" style="z-index: 1000; background-color: #444;">
    <div class="uk-position-center" uk-spinner></div>
</div>
<script>
    $(document).ready(function() {
        $('#page-loader').fadeOut(1000);
    })
</script>-->

app/views/pages/_navbar.html.erb
<div uk-sticky="sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky" style="height: 80px !important; z-index: 981;">
    <nav class="uk-navbar-container uk-visible@s" uk-navbar>
        <div class="uk-navbar-center" uk-scrollspy-nav="closest: li; offset: 90; overflow: true">
            <div class="uk-navbar-center-left">
                <ul class="uk-navbar-nav">
                    <li><a class="custom-font-1" href="#first-section" uk-scroll="offset: 80; duration: 800">Samples</a></li>
                    <li><a class="custom-font-1" href="#second-section" uk-scroll="offset: 80; duration: 800">Contact</a></li>
                </ul>
            </div>
            <h1 class="uk-navbar-item uk-logo uk-margin-remove handwriting">Krissi Flynn</h1>
            <div class="uk-navbar-center-right">
                <ul class="uk-navbar-nav">
                    <li><a class="custom-font-1" href="#third-section" uk-scroll="offset: 80; duration: 800">About Me</a></li>
                    <li><a class="custom-font-1" href="#fourth-section" uk-scroll="offset: 80; duration: 800">Links</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <nav class="uk-navbar-container uk-navbar-container uk-hidden@s">
        <div class="uk-navbar-left">
            <a class="uk-navbar-toggle">
                <span uk-navbar-toggle-icon></span> <span class="uk-margin-small-left">Menu</span>
            </a>
        </div>
        <div id="dropdown" class="uk-width-1-1" uk-dropdown="mode: click; offset: 0; animation: uk-animation-slide-top-small" style="z-index: 0;">
            <ul class="uk-nav uk-dropdown-nav">
                <li><a class="custom-font-1 uk-text-center dropdown-link" href="#first-section" uk-scroll="offset: 80; duration: 800">Samples</a></li>
                <li><a class="custom-font-1 uk-text-center dropdown-link" href="#second-section" uk-scroll="offset: 80; duration: 800">Contact</a></li>
                <li><a class="custom-font-1 uk-text-center dropdown-link" href="#third-section" uk-scroll="offset: 80; duration: 800">About Me</a></li>
                <li><a class="custom-font-1 uk-text-center dropdown-link" href="#fourth-section" uk-scroll="offset: 80; duration: 800">Links</a></li>
            </ul>
        </div>
    </nav>
</div>

app/views/pages/_parallax.html.erb
<div class="uk-background-cover uk-light uk-flex page-section-half" uk-parallax="bgy: 350" style="background-image: url(<%= image.url(:large) %>)"></div>

app/views/pages/_sample.html.erb
<%= link_to sample.image.url(:original), class: 'uk-child-width-1-1 uk-inline-clip uk-transition-toggle', caption: sample.caption, 'data-type' => 'image' do %>
    <%= image_tag sample.image.url(:thumb), alt: sample.alt %>
    <div class="uk-transition-slide-bottom uk-position-bottom uk-overlay uk-overlay-default">
        <p class="uk-h4 uk-margin-remove uk-text-center"><%= sample.category %></p>
    </div>
<% end %>

app/views/pages/_samples.html.erb
<div id="first-section" class="uk-height-1-1">
    <div class="uk-child-width-1-4@m uk-child-width-1-2@s uk-grid-collapse" uk-grid uk-lightbox="animation: slide">
        <% @samples.find_each do |s| %>
            <%= render 'sample', sample: s %>
        <% end %>
    </div>
</div>

app/views/pages/home.html.erb
<%= render 'loader' %>

<%= render 'navbar' %>

<%= render 'samples', cached: true %>

<%= render 'contact', cached: true %>

<%= render 'bio', cached: true %>

<%= render 'links' %>

<%= render 'footer' %>

<a uk-totop uk-scroll="duration: 800;" style="position: fixed; bottom: 30px; right: 30px;"></a>